### PR TITLE
Impl: Creating, Updating, Deleteing and Displaying User Tasks 

### PR DESCRIPTION
**Pull request by WizardAesthetics**
In this sprint we have implemented creating a task by making a form fo the user to fill out and when they click submit the task is stored in the database. We then implemented updating by clicking a button on the card we load a form with the information filled. We have a delete button that gets rid of a task. We are also grabing all tasks from the backend and displaying them.

### CODE REVIEW

**Review by Tootalll585 — APPROVED** [review]
Wow lots of code. Look good to me!

**Review by miriamshahine — APPROVED** [review]
Looks good

**Review by Abdul-Hai1 — COMMENTED** [review]
Looks good

**Review by raquelgrogan — COMMENTED** [review]
Looks good to me

**Review by nchrist5 — APPROVED** [review]
Looks good to me!

**Pull request merged**
