### PR TITLE
Install document

### PR DESCRIPTION
**Pull request by raquelgrogan**
This install document should contain all information and requirements needed to run this app. Fixes issue #5

### CODE REVIEW

**Review by Abdul-Hai1 — COMMENTED** [review]
Reviewed the changes and everything looks good

**Review by WizardAesthetics — APPROVED** [review]
Looks good, is very readable

**Comment by Tootalll585** [comment]
Looked it over. Looks great team!

**Review by miriamshahine — APPROVED** [review]
All the installations that we did are shown.

**Comment by nchrist5** [comment]
Issue #7
All installation procedures look good!

**Pull request merged**
