### PR TITLE
impl: Task Manager page, Sorting and filtering on dashboard, and bug fixes

### PR DESCRIPTION
**Pull request by Tootalll585**
Issue: #32 
1. Bug fixes/refactor
 * Create Task Bug
 * Display unique user tasks
 * Set Author equal to username
 * Complete will update field in database and remove card from Dashboard
 * Get Google sign in to work on the server

2. Dashboard Card Update
 * Make a todo button put it on the task card
 * If pressed remove from Dashboard 
 * Update a field in the database

3. Make the form for task manager
 * 3 columns with headers Todo/Active/Complete
 * Todo buttons mark as complete or active 
 * Active buttons mark as todo or complete

4. Dash board enhancements 
 * The user should be able to filter the tasks on the dashboard by category or sort them by date.

### CODE REVIEW

**Review by Abdul-Hai1 — COMMENTED** [review]
Looks good

**Review by miriamshahine — APPROVED** [review]
Looks good

**Review by WizardAesthetics — APPROVED** [review]
I have looked over everything and approve these changes

**Review by nchrist5 — APPROVED** [review]
Everything looks good and is working correctly. Go team!

**Pull request merged**
