### PR TITLE
project_layout: added file structure for project layout

### PR DESCRIPTION
**Pull request by nchrist5**
Added skeleton folders for the project

We followed the 'Group by Archetype' found at https://www.nikolaposa.in.rs/blog/2017/01/16/on-structuring-php-projects/
Each folder is set up for the specific module that we will be creating. We may need to add additional module folders in the future as we expand the project.

### CODE REVIEW

**Comment by nchrist5** [comment]
Server/Controllers folder:
The controllers contain the different requests handled by the server such as: CreateTask, UpdateTask, DeleteTask etc.

**Comment by WizardAesthetics** [comment]
issue #8 client/scr/API.js is how the client and server connects. You will package user data the API will grab it and send it to the server.

**Comment by Tootalll585** [comment]
Issue #8 
/server/routes
 - This folder will be the location for all of our routing. We will be using this folder to hold webpage routes when the user clicks on a link or submits a task on the webapp.

**Comment by Abdul-Hai1** [comment]
issue #8 

/client/components:
This folder will contain the code for the different components that are displayed on the web page. For example, a login box with a "sign in" button or a "register" button would be a component. So the components folder would contain the code for the styling and display of the login box, and also reference to the appropriate file/code for when the button is clicked.

**Comment by miriamshahine** [comment]
issue #8 
src/images 
images are important because they make the project more presentable for the user. A feature of the images could be a place to store profile photos, if we choose to do that.  We could also give the user the ability to upload their own photos for each task.

**Review by WizardAesthetics — COMMENTED** [review]
Looks good

**Comment by raquelgrogan** [comment]
Issue #6 : server/models folder : Files in the model folder will take care of the incoming requests and convert it into data that the controller can use.

**Pull request merged**
