### PR TITLE
Gitignore setup

### PR DESCRIPTION
**Pull request by nchrist5**
Issue#1

Initial .gitignore setup with team

Added Secure Credentials & .ssh keys
Added VSCode Application Files & Local History
Added WindowsOS Files
Added Environments
Added Installed Package Files
Added Ignored Logs
Added Build Directory

### CODE REVIEW

**Comment by miriamshahine** [comment]
Issue #1-
 .gitignore looks good

**Comment by Tootalll585** [comment]
Issue #1-
I have reviewed the gitignore file. I dont see any issues with the file at this time.

**Comment by Abdul-Hai1** [comment]
Issue #4:
I've reviewed the gitignore file and it looks good

**Comment by WizardAesthetics** [comment]
issue #4 Ive looked over the .gitigoore and everything looks good.

**Comment by raquelgrogan** [comment]
Issue #4 - This successfully adds a .gitignore file to our project

**Review by raquelgrogan — COMMENTED** [review]
This fixes issue #4: .gitignore added with no errors

**Review by Tootalll585 — COMMENTED** [review]
reviewed.

**Pull request merged**
